Optimize package installation
Catrobat/Gradle pull request #6
Opened 2019-04-01 19:57 UTC by dwb357

Optimize package installation by tracking which packages have been installed (during this run) and not attempting to reinstall them.  Quick way around the current n log n process.

2019-04-03 19:25 UTC, mfuchs commented
Thank you for the PR. :)

What does your gradle command look like so that the same packages are installed multiple times?

2019-04-03 20:38 UTC, dwb357 commented
Not so much the command as that I have multiple emulators defined and the way the code is set up it installs:

* emulator1 image
* emulator1 image
* emulator2 image
* emulator1 image
* emulator2 image
* emulator3 image

etc.  each new emulator causes every prior emulator image to also be reinstalled.  There are more correct ways to fix it, but this also catches the case where you have multiple emulators that use the same image (ie., a phone and tablet, both on 23)

David W. Berry
dwb@Greenwing.com

> On Apr 3, 2019, at 14:25, Matthias Fuchs <notifications@github.com> wrote:
> 
> Thank you for the PR. :)
> 
> What does your gradle command look like so that the same packages are installed multiple times?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-04-07 16:17 UTC, mfuchs requested changes
Again thanks for the PR.
Please squash together the first and third commit, that makes the history easier to understand.

2019-04-07 16:17 UTC, mfuchs commented on android-emulators-gradle/src/main/groovy/org/catrobat/gradle/androidemulators/EmulatorsPluginExtension.groovy
> +        if(installer == null) {
Please add a space after the if.

2019-04-07 16:17 UTC, mfuchs commented on android-emulators-gradle/src/main/groovy/org/catrobat/gradle/androidemulators/Installer.groovy
> +        if(packages.empty) {
Please add a space there as well.

2025-02-26 17:08 UTC, closed without merging